### ISSUE TITLE
Input to reshape is a tensor with 1328 values, but the requested shape requires a multiple of 528 

### ISSUE THREAD

**Issue by GuillaumeDes** [learningmatter-mit/peptimizer#4]
Hi, 
I am trying to run the code Tutorial_Synthesis.ipynb

When I try to change the SEQ_MAX parameter (for example, to 100), the code returns the error : 
`Traceback (most recent call last):
  File "/home/guillaume/PycharmProjects/peptimizer/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1328 values, but the requested shape requires a multiple of 528
	 [[{{node flatten_1/Reshape}}]]`
	 
Do you have any idea how to solve it ?

**Comment by pikulsomesh** [comment]
You could check the changes in tensor shape across the different layers, and change the convolution layer hyperparameters accordingly. See [link](https://stackoverflow.com/questions/43010339/python-tensorflow-input-to-reshape-is-a-tensor-with-92416-values-but-the-re).
