### ISSUE TITLE
Blank in the optimized sequences

### ISSUE THREAD

**Issue by sunghunbae** [learningmatter-mit/peptimizer#5]
The optimization generates a lot of sequences with ' '(blank) at the C-terminal end. 
In the below example, a blank character follows ...GKK in the first sequence. This blank is counted as an amino acid sequence and its length is 10 while the second sequence does not have the blank and its length is 9. I am wondering if the blank affects the intensity.

sequences,intensity,length,relative_Arg,relative_charge
KKPCHHGKK ,6.252917870132182,10,0.0,0.554286151848062
KKPCHHMKK,6.177834318018949,9,0.0,0.6158735020534022

**Comment by pikulsomesh** [comment]
The blank or whitespace does not affect the intensity, as the [fingerprint for whitespace](https://github.com/learningmatter-mit/peptimizer/blob/bbca91b425934f1368e5a574fb7d8b380381102d/utils/utils_common/fingerprint_2d.py#L20) is a vector of 0s, similar to the one used for padding.
