### ISSUE TITLE
PMO-CPP library and activity dataset

### ISSUE THREAD

**Issue by Jiacheng06** [learningmatter-mit/peptimizer#6]
Hi pikulsomesh,

I was wondering if the dataset of PMO-CPP library and activity (from the paper: Deep Learning Enables Discovery of a Short Nuclear Targeting Peptide for Efficient Delivery of Antisense Oligomers) is open to public? If so, could you please tell me how to download it because I could not find it in the current dataset.

Thanks a lot,
Jiacheng

**Comment by pikulsomesh** [comment]
Hi @Jiacheng06 
The dataset of PMO-CPP library consists of both the [dataset](https://github.com/learningmatter-mit/peptimizer/blob/master/dataset/data_cpp/cpp_predictor_dataset.csv) in the GitHub repository, and the sequences published in the original [paper](https://www.nature.com/articles/s41557-021-00766-3), specifically in Table 13 of [Supplementary Information](https://static-content.springer.com/esm/art%3A10.1038%2Fs41557-021-00766-3/MediaObjects/41557_2021_766_MOESM1_ESM.pdf).
Best
Somesh

**Comment by Jiacheng06** [comment]
Hi Somesh,

Thank you very much for your promptly reply! I was also wondering about the meaning of some numbers (like 2 and 3) in the sequences of the cpp_predictor_dataset. BTW, does the dataset of PMO-CPP library only include the sequences of CPPs without PMO (which means during the training of the model, it only uses the sequences of CPPs)?

Kind regards,
Jiacheng
