### ISSUE TITLE
duplicate seqs with abnormal difference on cpp_predictor_dataset

### ISSUE THREAD

**Issue by rocke2020** [learningmatter-mit/peptimizer#7]
Hi, Somesh

First of all, thanks for your excellent paper, the regression predictor and genetic loop selection delight me very much, an indeed innovation, comparing other binary classifiers on this fields. The 600 experiments are the base of this innovation.

thanks for your shared codes, I find a issue  the cpp_predictor_dataset.
Among the 512 seqs with intensity value in cpp_predictor_dataset.csv.
23 seqs are duplicates, some duplicate seqs with huge value differences. 
The min intensity is 0.3 and max 19.3 for all the 512 seqs experiments.
AGYLLGKINLKALAALAKKIL2KRVK3RQIKIWFQNRRMKWKK,0.9058188362327536
AGYLLGKINLKALAALAKKIL2KRVK3RQIKIWFQNRRMKWKK,1.259748050389922
AGYLLGKINLKALAALAKKIL2KRVK3RQIKIWFQNRRMKWKK,12.370725854829034
Does it means you do three experiments for the same one seq and get three different values?

thanks!!

**Comment by pikulsomesh** [comment]
The CPP data files have been updated, and complete information on the preparation of the data has been provided here - https://github.com/learningmatter-mit/peptimizer/tree/master/dataset/data_cpp
