### ISSUE TITLE
How to define cross linkers?

### ISSUE THREAD

**Issue by amin-sagar** [learningmatter-mit/peptimizer#8]
Thanks for this awesome work.

Is there some documentation about how to define chemical crosslinkers?

I think the residue "2" in [cpp_smiles.json](https://github.com/learningmatter-mit/peptimizer/blob/master/dataset/data_cpp/cpp_smiles.json) is a cross linker. Can you please help me in understanding the general way to describe the chemical crosslinkers and the residues which get crosslinked.

Do you think it could be possible to define some chemical crosslinkers that link more that two residues, for example 3 cysteines.

I would be really grateful for any suggestions.

Best,
Amin.

**Comment by pikulsomesh** [comment]
@amin-sagar In this case, we defined the crosslinkers at the place they were appearing on the sequence. 

As you can note in the [dataset](https://github.com/learningmatter-mit/peptimizer/blob/master/dataset/data_cpp/cpp_predictor_dataset.csv) we had linkers joining 2 residues at once only. Thus, we defined them as is. 

However, for linkers joining 3 or more residues, we developed a more generalized graph representation, where you could define more complex peptides and macromolecules. The paper is [here](https://iopscience.iop.org/article/10.1088/2632-2153/ac545e) and the GitHub repository is [here](https://github.com/learningmatter-mit/GLAMOUR/).
